# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 - azure

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  
- task: CmdLine@2
  inputs:
    script: 'docker pull devexpress/devextreme-build:19_1
      
      docker run -t -e HEADLESS=true -e TARGET=test -v $(Build.SourcesDirectory):/devextreme devexpress/devextreme-build:19_1 ./docker-ci.sh'
  displayName: 'Run test'
